import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { fromImageToUrl, API_URL } from "@/utils/urls";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ clothing }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {clothing.data.map(clothes => (
        <div key={clothes.Title} className={styles.clothes}>
          <div className={styles.clothes__Row}>
            <div className={styles.clothes__ColImg}>
              <img src={fromImageToUrl(clothes.attributes.image)} />
            </div>
            <div className={styles.clothes__Col}>
              {clothes.attributes.Title}: {clothes.attributes.type}
            </div>
          </div>
        </div>
      ))}
      {/* {JSON.stringify(clothing)} */}
    </>
  );
}

export async function getStaticProps() {
  const clothes_res = await fetch(`${API_URL}/api/clothes?populate=*`)
  const clothing = await clothes_res.json()
  return{
    props: {
      clothing
    }
  }
}